name: BennettSecrest
favicon: null
layout_spectrum: 0.6404709569178522
typography_spectrum: 0.21261147572658956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.031319328118115664
  lightness: 0.20583479711785913
  saturation: 0.0636871992610395
  rhythmicContrast: 0.5893273609690368
purpose: []
